// <auto-generated />
using System;
using ErpOnlineOrder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpOnlineOrder.Infrastructure.Migrations
{
    [DbContext(typeof(ErpOnlineOrderDbContext))]
    partial class ErpOnlineOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<string>("Email_author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pen_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<string>("birth_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("death_date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Cover_type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cover_type_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoverTypes", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<string>("Customer_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("Id");

                    b.HasIndex("User_id")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer_category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int")
                        .HasColumnName("Category_id");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<decimal?>("Discount_percent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category_id");

                    b.HasIndex("Customer_id", "Category_id")
                        .IsUnique();

                    b.ToTable("CustomerCategories", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer_management", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Province_id")
                        .HasColumnType("int")
                        .HasColumnName("Province_id");

                    b.Property<int>("Staff_id")
                        .HasColumnType("int")
                        .HasColumnName("Staff_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Customer_id");

                    b.HasIndex("Province_id");

                    b.HasIndex("Staff_id", "Customer_id")
                        .IsUnique();

                    b.ToTable("CustomerManagements", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer_product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<decimal?>("Custom_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<decimal?>("Discount_percent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Max_quantity")
                        .HasColumnType("int");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Customer_id", "Product_id")
                        .IsUnique();

                    b.ToTable("CustomerProducts", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<string>("Distributor_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Distributor_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Distributor_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Distributors", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<string>("Invoice_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Invoice_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Merged_into_invoice_id")
                        .HasColumnType("int")
                        .HasColumnName("Merged_into_invoice_id");

                    b.Property<int?>("Order_id")
                        .HasColumnType("int")
                        .HasColumnName("Order_id");

                    b.Property<int?>("Parent_invoice_id")
                        .HasColumnType("int")
                        .HasColumnName("Parent_invoice_id");

                    b.Property<string>("Split_merge_note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Staff_id")
                        .HasColumnType("int")
                        .HasColumnName("Staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Tax_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<int?>("Warehouse_export_id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse_export_id");

                    b.HasKey("Id");

                    b.HasIndex("Customer_id");

                    b.HasIndex("Merged_into_invoice_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("Parent_invoice_id");

                    b.HasIndex("Staff_id");

                    b.HasIndex("Warehouse_export_id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Invoice_detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Invoice_id")
                        .HasColumnType("int")
                        .HasColumnName("Invoice_id");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax_rate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Invoice_id");

                    b.HasIndex("Product_id");

                    b.ToTable("InvoiceDetails", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Order_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Order_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Order_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Shipping_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_amount")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Customer_id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Order_detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order_id")
                        .HasColumnType("int")
                        .HasColumnName("Order_id");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax_rate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Order_id");

                    b.HasIndex("Product_id");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Organization_information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Organization_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Organization_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Recipient_address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Recipient_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Recipient_phone")
                        .HasColumnType("int");

                    b.Property<int>("Tax_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Customer_id");

                    b.ToTable("OrganizationInformations", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Action_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Module_id")
                        .HasColumnType("int");

                    b.Property<string>("Permission_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cover_type_id")
                        .HasColumnType("int")
                        .HasColumnName("Cover_type_id");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int?>("Distributor_id")
                        .HasColumnType("int")
                        .HasColumnName("Distributor_id");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Product_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Product_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Product_price")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Publisher_id")
                        .HasColumnType("int")
                        .HasColumnName("Publisher_id");

                    b.Property<decimal?>("Tax_rate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cover_type_id");

                    b.HasIndex("Distributor_id");

                    b.HasIndex("Publisher_id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product_author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Author_id")
                        .HasColumnType("int")
                        .HasColumnName("Author_id");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Author_id");

                    b.HasIndex("Product_id");

                    b.ToTable("ProductAuthors", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product_category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int")
                        .HasColumnName("Category_id");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category_id");

                    b.HasIndex("Product_id");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product_image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_primary")
                        .HasColumnType("bit")
                        .HasColumnName("Is_main");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<int>("Sort_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image_url");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Province_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Region_id")
                        .HasColumnType("int")
                        .HasColumnName("Region_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Region_id");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Publisher_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Region_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Region_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Role_permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_at");

                    b.Property<int>("Created_by")
                        .HasColumnType("int")
                        .HasColumnName("Created_by");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Is_deleted");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_at");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int")
                        .HasColumnName("Updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<string>("Full_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Staff_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("Id");

                    b.HasIndex("User_id")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<int>("Warehouse_id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Warehouse_id");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_at");

                    b.Property<int>("Created_by")
                        .HasColumnType("int")
                        .HasColumnName("Created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("bit")
                        .HasColumnName("Is_active");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_at");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int")
                        .HasColumnName("Updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.User_permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.User_role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Role_id")
                        .HasColumnType("int")
                        .HasColumnName("Role_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("Id");

                    b.HasIndex("Role_id");

                    b.HasIndex("User_id");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Province_id")
                        .HasColumnType("int")
                        .HasColumnName("Province_id");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<string>("Warehouse_address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Warehouse_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Warehouse_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Province_id");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse_export", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<string>("Delivery_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Export_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Invoice_id")
                        .HasColumnType("int")
                        .HasColumnName("Invoice_id");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Merged_into_export_id")
                        .HasColumnType("int")
                        .HasColumnName("Merged_into_export_id");

                    b.Property<int?>("Order_id")
                        .HasColumnType("int")
                        .HasColumnName("Order_id");

                    b.Property<int?>("Parent_export_id")
                        .HasColumnType("int")
                        .HasColumnName("Parent_export_id");

                    b.Property<string>("Split_merge_note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Staff_id")
                        .HasColumnType("int")
                        .HasColumnName("Staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tracking_number")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<string>("Warehouse_export_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Warehouse_id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("Customer_id");

                    b.HasIndex("Invoice_id");

                    b.HasIndex("Merged_into_export_id");

                    b.HasIndex("Order_id");

                    b.HasIndex("Parent_export_id");

                    b.HasIndex("Staff_id");

                    b.HasIndex("Warehouse_id");

                    b.ToTable("WarehouseExports", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse_export_detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Created_by")
                        .HasColumnType("int");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<int>("Quantity_shipped")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated_by")
                        .HasColumnType("int");

                    b.Property<int>("Warehouse_export_id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse_export_id");

                    b.Property<int>("Warehouse_id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouse_id");

                    b.HasKey("Id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Warehouse_export_id");

                    b.HasIndex("Warehouse_id");

                    b.ToTable("WarehouseExportDetails", (string)null);
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("ErpOnlineOrder.Domain.Models.Customer", "User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer_category", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Category", "Category")
                        .WithMany("Customer_Categories")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany("Customer_Categories")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer_management", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany("Customer_managements")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Province", "Province")
                        .WithMany("Customer_managements")
                        .HasForeignKey("Province_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Staff", "Staff")
                        .WithMany("Customer_managements")
                        .HasForeignKey("Staff_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Province");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer_product", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany("Customer_Products")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Customer_Products")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Invoice", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Invoice", "Merged_into_invoice")
                        .WithMany("Merged_invoices")
                        .HasForeignKey("Merged_into_invoice_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Invoice", "Parent_invoice")
                        .WithMany("Child_invoices")
                        .HasForeignKey("Parent_invoice_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Staff", "Staff")
                        .WithMany("Invoices")
                        .HasForeignKey("Staff_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse", "Warehouse_export")
                        .WithMany()
                        .HasForeignKey("Warehouse_export_id");

                    b.Navigation("Customer");

                    b.Navigation("Merged_into_invoice");

                    b.Navigation("Order");

                    b.Navigation("Parent_invoice");

                    b.Navigation("Staff");

                    b.Navigation("Warehouse_export");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Invoice_detail", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Invoice", "Invoice")
                        .WithMany("Invoice_Details")
                        .HasForeignKey("Invoice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Invoice_Details")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Order", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Order_detail", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Order", "Order")
                        .WithMany("Order_Details")
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Order_Details")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Organization_information", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany("Organization_informations")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Cover_type", "Cover_type")
                        .WithMany("Products")
                        .HasForeignKey("Cover_type_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Distributor", "Distributor")
                        .WithMany("Products")
                        .HasForeignKey("Distributor_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Publisher", "Publisher")
                        .WithMany("Products")
                        .HasForeignKey("Publisher_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cover_type");

                    b.Navigation("Distributor");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product_author", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Author", "Author")
                        .WithMany("Product_Authors")
                        .HasForeignKey("Author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Product_Authors")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product_category", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Category", "Category")
                        .WithMany("Product_Categories")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Product_Categories")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product_image", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Product_Images")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Province", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Region", "Region")
                        .WithMany("Provinces")
                        .HasForeignKey("Region_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Role_permission", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Permission", "Permission")
                        .WithMany("Role_Permissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Role", "Role")
                        .WithMany("Role_Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Staff", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("ErpOnlineOrder.Domain.Models.Staff", "User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Stock", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("Warehouse_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.User_permission", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Permission", "Permission")
                        .WithMany("User_Permissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.User", "User")
                        .WithMany("User_permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.User_role", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Role", "Role")
                        .WithMany("User_roles")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.User", "User")
                        .WithMany("User_roles")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("Province_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse_export", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("Invoice_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse_export", "Merged_into_export")
                        .WithMany("Merged_exports")
                        .HasForeignKey("Merged_into_export_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse_export", "Parent_export")
                        .WithMany("Child_exports")
                        .HasForeignKey("Parent_export_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErpOnlineOrder.Domain.Models.Staff", "Staff")
                        .WithMany("Warehouse_exports")
                        .HasForeignKey("Staff_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("Warehouse_Exports")
                        .HasForeignKey("Warehouse_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("Merged_into_export");

                    b.Navigation("Order");

                    b.Navigation("Parent_export");

                    b.Navigation("Staff");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse_export_detail", b =>
                {
                    b.HasOne("ErpOnlineOrder.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse_export", "Warehouse_export")
                        .WithMany("Warehouse_Export_Details")
                        .HasForeignKey("Warehouse_export_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpOnlineOrder.Domain.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");

                    b.Navigation("Warehouse_export");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Author", b =>
                {
                    b.Navigation("Product_Authors");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Category", b =>
                {
                    b.Navigation("Customer_Categories");

                    b.Navigation("Product_Categories");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Cover_type", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Customer", b =>
                {
                    b.Navigation("Customer_Categories");

                    b.Navigation("Customer_Products");

                    b.Navigation("Customer_managements");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Organization_informations");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Distributor", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Invoice", b =>
                {
                    b.Navigation("Child_invoices");

                    b.Navigation("Invoice_Details");

                    b.Navigation("Merged_invoices");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Permission", b =>
                {
                    b.Navigation("Role_Permissions");

                    b.Navigation("User_Permissions");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Product", b =>
                {
                    b.Navigation("Customer_Products");

                    b.Navigation("Invoice_Details");

                    b.Navigation("Order_Details");

                    b.Navigation("Product_Authors");

                    b.Navigation("Product_Categories");

                    b.Navigation("Product_Images");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Province", b =>
                {
                    b.Navigation("Customer_managements");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Publisher", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Region", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Role", b =>
                {
                    b.Navigation("Role_Permissions");

                    b.Navigation("User_roles");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Staff", b =>
                {
                    b.Navigation("Customer_managements");

                    b.Navigation("Invoices");

                    b.Navigation("Warehouse_exports");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Staff");

                    b.Navigation("User_permissions");

                    b.Navigation("User_roles");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("Warehouse_Exports");
                });

            modelBuilder.Entity("ErpOnlineOrder.Domain.Models.Warehouse_export", b =>
                {
                    b.Navigation("Child_exports");

                    b.Navigation("Merged_exports");

                    b.Navigation("Warehouse_Export_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
